version: 2.1
workflows:
  main:
    jobs:
      - build
jobs:
  build:
    docker:
      - image: python:3.9.4
    # machine:
    #   image: ubuntu-2004:202107-02

    steps:
      - checkout
      
      - setup_remote_docker:
          version: 20.10.12
          docker_layer_caching: true

      - run: echo "Do some things"

      - run:
          name: Checking Linux Version
          command: |
            cat /etc/os-release
            echo -e ".\n.\n.\n"
            uname -a

      - run:
          name: Installing Docker
          command: |
            set -x
            curl -fsSL https://get.docker.com -o get-docker.sh
            DRY_RUN=1 sh ./get-docker.sh
            sh get-docker.sh

      - run:
          name: Checking Docker Version
          command: docker --version

      - run:
          name: Install Docker Compose
          command: |
            set -x
            VER="1.29.2"
            curl -L https://github.com/docker/compose/releases/download/$VER/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose

      - run:
          name: Check Docker Compose Version
          command: docker-compose --version
