version: 2.1
workflows:
  main:
    jobs:
      - build
jobs:
  build:
    machine:
      image: ubuntu-2004:202107-02
    steps:
      - checkout

      - run: echo "Do some things"

      - run:
          name: Checking Docker Version
          command: docker --version

      - run:
          name: Checking Linux Version
          command: |
            cat /etc/os-release
            echo ".\n.\n.\n"
            uname -a
